version: '3'
services:
  web:
    build: ./app/web_service
    ports:
      - "5001:5001"
    networks:
      - internal_network
    env_file:
      - .env

  embedder:
    build: ./app/embedding_service
    volumes:
      - model_data:/app/model_data
    networks:
      - internal_network
    env_file:
      - .env

  searcher:
    build: ./app/search_service
    depends_on:
      - doc_db
    volumes:
      - index_data:/app/index_data/
    networks:
      - internal_network
    env_file:
      - .env

  doc_db:
    build: ./app/db_service
    volumes:
      - db_data:/app/db_data
    networks:
      - internal_network
    env_file:
      - .env

  ingestor:
    build: ./app/ingestion_service
    networks:
      - internal_network
    env_file:
      - .env

  llm_chat:
    build: ./app/llm_service
    # TODO: add a volume and preload with model to avoid copying every time it needs to be built
    networks:
      - internal_network
    env_file:
      - .env

networks:
  internal_network:
    driver: bridge

volumes:
  model_data:
  index_data:
  db_data: